export declare function addItem(jsonQuery: any): Promise<any>;
export declare function removeItem(jsonQuery: any): Promise<any>;
export declare function getItem(jsonQuery: any): Promise<any>;
export declare function getAllItems(): Promise<any>;
export declare function addUser(jsonQuery: any): Promise<any>;
export declare function removeUser(jsonQuery: any): Promise<any>;
export declare function getUser(jsonQuery: any): Promise<any>;
export declare function getAllUsers(): Promise<any>;
export declare function apiCall(url: any, requestBody?: any): Promise<any>;
export declare function firebaseApiCall(tableName: any, params: any): Promise<any>;
